////////////////////////////Prj Info////////////////////////////
#/*****************/which project you want to build,you can choose[ xilinx intel ]
xilinx
///////////////////////////LIB Config///////////////////////////
#/*****************/if include Soc,you can choose [ none ] or [ cortexM3 cortexA9 ] + { -prj_name test -os standalone -app HelloWorld}
Soc
none
#/*****************/if include DSP,you can choose 0/1
DSP
0
#/*****************/if include Driver,you can choose 0/1
Driver
0
///////////////////////////Run Config///////////////////////////
#/*****************/Whether to display logs during compilation   yes/no
Showlog
no
#/*****************/download typle TEST  BOOT
Download
TEST
#/*****************/flash typle
Flash
TEST
#/*****************/The info of device Note: auto generate do not touch
Device
