# workspace for slang
FROM ubuntu:22.04
RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y g++-9 \
    && apt-get install -y cmake \
    && apt-get install -y vim \
    && apt-get install -y python3 \
    && apt-get install -y git \
    && apt-get install -y curl \